name: reveal_card
description: Card Widget with a Front Side and a Back Side. The Back side will be revealed with an animation on button click.
version: 1.0.0
homepage: https://github.com/Tharun-GS/reveal_card

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: